name: CI Build Push Strapi

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" \
          | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/strapi-task6:${{ steps.meta.outputs.tag }} .

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/strapi-task6:${{ steps.meta.outputs.tag }}

